# Generated by Django 4.1.5 on 2023-01-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amountPages',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publicationDate',
            field=models.DateField(blank=True),
        ),
    ]
