# Generated by Django 4.1.5 on 2023-01-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_book_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Menu.genres'),
        ),
    ]
