# Generated by Django 4.1.5 on 2023-01-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_genres_alter_book_genres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
    ]
