# Generated by Django 4.1.5 on 2023-01-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0008_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Menu.genre'),
            preserve_default=False,
        ),
    ]
