# Generated by Django 4.1.5 on 2023-01-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0010_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
