# Generated by Django 4.1.5 on 2023-01-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0011_alter_genre_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeteleBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Menu.book')),
            ],
        ),
    ]
