# Generated by Django 4.1.5 on 2023-01-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0012_detelebook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeteleBook',
            new_name='DeleteBook',
        ),
    ]
