# Generated by Django 4.1.5 on 2023-01-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0013_rename_detelebook_deletebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeleteBook',
        ),
    ]
