# Generated by Django 4.1.5 on 2023-01-12 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0014_delete_deletebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amountPages',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Menu.genre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='publicationDate',
            field=models.DateField(default=datetime.date(2023, 1, 12)),
            preserve_default=False,
        ),
    ]
