# Generated by Django 4.1.5 on 2023-01-13 17:48

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0016_alter_author_birthdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('firstName'), django.db.models.functions.text.Lower('lastName'), name='full_name', violation_error_message='Este autor já está cadastrado no sistema. Por favor, cadastre outro.'),
        ),
        migrations.AddConstraint(
            model_name='genre',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='name', violation_error_message='Este Gênero já está cadastrado no sistema. Por favor, cadastre outro.'),
        ),
    ]
