# Generated by Django 4.1.5 on 2023-01-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0017_alter_genre_options_author_full_name_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rent',
            field=models.BooleanField(default=False),
        ),
    ]
